name: Sync CV from Overleaf

on:
  schedule:            # runs at 08:00 UTC daily
    - cron: '0 8 * * *'
  workflow_dispatch:    # allow manual trigger

jobs:
  update-cv:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout website
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_PAT }}

    - name: Clone Overleaf project
      run: |
        git clone \
          https://:${{ secrets.OVERLEAF_TOKEN }}@${{ secrets.OVERLEAF_GIT_URL}} \
          overleaf

    - name: Copy latest PDF into site
      run: |
        cp overleaf/CV_Joel_Eliason.pdf assets/docs/cv.pdf

    - name: Commit & push if changed
      run: |
        git config user.name  "github-actions[bot]"
        git config user.email "actions@github.com"
        if ! git diff --quiet; then
          git add assets/docs/cv.pdf
          git commit -m "Auto-update CV from Overleaf"
          git push
        else
          echo "No changes to commit"
        fi
